# Generated by Django 5.2.17 on 2026-09-11 19:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='GroupeEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('annee_universitaire', models.CharField(help_text='Ex. : 2025-2026', max_length=20)),
            ],
            options={
                'verbose_name': "groupe d'etudiants",
                'ordering': ['annee_universitaire', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CampagneEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('semestre', models.CharField(blank=True, max_length=20)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('programmee', 'Programmee'), ('active', 'Active'), ('fermee', 'Fermee')], default='brouillon', max_length=20)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campagnes', to='evaluations.enseignant')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campagnes', to='evaluations.groupeetudiant')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campagnes', to='evaluations.module')),
            ],
            options={
                'verbose_name': "campagne d'evaluation",
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='QuestionEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=300)),
                ('type_question', models.CharField(choices=[('note', 'Note (1 a 5)'), ('texte', 'Texte libre')], default='note', max_length=10)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='evaluations.campagneevaluation')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ReponseEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_anonyme', models.CharField(db_index=True, max_length=64)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='evaluations.campagneevaluation')),
            ],
            options={
                'verbose_name': "reponse d'evaluation",
                'unique_together': {('campagne', 'identifiant_anonyme')},
            },
        ),
        migrations.CreateModel(
            name='EvaluateurAutorise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_anonyme', models.CharField(db_index=True, max_length=64)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluateurs_autorises', to='evaluations.campagneevaluation')),
            ],
            options={
                'verbose_name': 'evaluateur autorise',
                'unique_together': {('campagne', 'identifiant_anonyme')},
            },
        ),
        migrations.CreateModel(
            name='ReponseQuestionEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reponse_texte', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.questionevaluation')),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='evaluations.reponseevaluation')),
            ],
            options={
                'verbose_name': "reponse a une question d'evaluation",
                'unique_together': {('reponse', 'question')},
            },
        ),
    ]
