# Generated by Django 5.2.17 on 2026-09-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='campagneevaluation',
            constraint=models.CheckConstraint(condition=models.Q(('date_debut__isnull', True), ('date_fin__isnull', True), ('date_fin__gt', models.F('date_debut')), _connector='OR'), name='eval_campagne_fin_apres_debut'),
        ),
    ]
