# Generated by Django 5.2.17 on 2026-09-13 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_contraintes_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupeetudiant',
            name='filiere',
            field=models.CharField(blank=True, help_text='Ex. : Genie Informatique, Genie Civil', max_length=80),
        ),
        migrations.CreateModel(
            name='EtudiantInterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('filiere', models.CharField(max_length=80)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='evaluations.groupeetudiant')),
            ],
            options={
                'verbose_name': 'etudiant interne',
                'ordering': ['groupe', 'nom', 'prenom'],
            },
        ),
    ]
