# Generated by Django 5.2.17 on 2026-09-11 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilConseiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(blank=True, max_length=150, verbose_name="domaine d'accompagnement")),
                ('biographie', models.TextField(blank=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_conseiller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil conseiller',
            },
        ),
        migrations.CreateModel(
            name='DisponibiliteConseiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure_debut', models.DateTimeField()),
                ('date_heure_fin', models.DateTimeField()),
                ('est_disponible', models.BooleanField(default=True)),
                ('conseiller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='conseil.profilconseiller')),
            ],
            options={
                'verbose_name': 'disponibilite conseiller',
                'ordering': ['date_heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rendez_vous', models.DateTimeField()),
                ('motif', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('confirme', 'Confirme'), ('annule', 'Annule'), ('termine', 'Termine')], default='confirme', max_length=20)),
                ('note_conseiller', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='candidats.profilcandidat')),
                ('conseiller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='conseil.profilconseiller')),
                ('disponibilite', models.OneToOneField(blank=True, help_text='Un creneau ne peut etre reserve qu une seule fois.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='conseil.disponibiliteconseiller')),
            ],
            options={
                'verbose_name': 'rendez-vous',
                'ordering': ['date_rendez_vous'],
            },
        ),
    ]
