# Generated by Django 5.2.17 on 2026-09-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conseil', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='disponibiliteconseiller',
            constraint=models.CheckConstraint(condition=models.Q(('date_heure_fin__gt', models.F('date_heure_debut'))), name='conseil_dispo_fin_apres_debut'),
        ),
    ]
