# Generated by Django 5.2.17 on 2026-09-11 19:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('domaine', models.CharField(max_length=150, verbose_name='pole / domaine')),
                ('niveau', models.CharField(choices=[('prepa', 'Cycle preparatoire'), ('ingenieur', 'Cycle ingenieur'), ('licence', 'Licence'), ('master', 'Master')], max_length=20)),
                ('parcours', models.CharField(blank=True, help_text='Ex. : Prepa + Cycle Ingenieur, Licence + Master, admission parallele', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('conditions_admission', models.TextField(blank=True)),
                ('competences_recherchees', models.TextField(blank=True)),
                ('debouches', models.TextField(blank=True)),
                ('est_active', models.BooleanField(default=True)),
                ('matieres_importantes', models.ManyToManyField(blank=True, related_name='formations', to='candidats.matiere')),
                ('parent', models.ForeignKey(blank=True, help_text='Filiere parente (ex. : Genie Informatique pour Web & Mobile).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialisations', to='formations.formation')),
            ],
            options={
                'verbose_name': 'formation',
                'ordering': ['domaine', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='PrerequisFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_minimale', models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('poids', models.PositiveIntegerField(default=1, help_text='Importance relative de la matiere pour cette formation.')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequis', to='formations.formation')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequis', to='candidats.matiere')),
            ],
            options={
                'verbose_name': 'prerequis de formation',
                'unique_together': {('formation', 'matiere')},
            },
        ),
    ]
