# Generated by Django 5.2.17 on 2026-09-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='reconnaissance',
            field=models.CharField(choices=[('reconnue', "Reconnue par l'Etat"), ('accreditee', 'Accreditee uniquement')], default='reconnue', help_text="Les candidats visee universite publique ou emploi public ne voient que les formations reconnues par l'Etat.", max_length=20),
        ),
    ]
