# Generated by Django 5.2.17 on 2026-09-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_parcours_reconnue_ia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='reconnaissance',
            field=models.CharField(choices=[('reconnue', "Reconnue par l'Etat"), ('accreditee', 'Accreditee uniquement')], default='reconnue', help_text="Les projets universite publique, fonction publique et ecole reconnue ne voient que les formations reconnues par l'Etat. Le secteur prive voit aussi les formations accreditees.", max_length=20),
        ),
    ]
