# Generated by Django 5.2.17 on 2026-09-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0003_objectifs_prive_reconnue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='reconnaissance',
            field=models.CharField(choices=[('reconnue', "Reconnue par l'Etat"), ('accreditee', 'Accreditee uniquement')], default='reconnue', help_text="Projet public : formations reconnues par l'Etat. Projet prive : les formations accreditees sont aussi proposees.", max_length=20),
        ),
    ]
