# Generated by Django 5.2.17 on 2026-09-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0004_deux_objectifs'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='image',
            field=models.ImageField(blank=True, help_text='Affichee sur le catalogue candidat et dans l administration.', upload_to='formations/', verbose_name='image de couverture'),
        ),
    ]
