# Generated by Django 5.2.17 on 2026-09-11 19:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'matiere',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CentreInteret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('domaine', "Domaine d'interet"), ('activite', "Preference d'activite")], default='domaine', max_length=20)),
            ],
            options={
                'verbose_name': "centre d'interet",
                'ordering': ['categorie', 'nom'],
                'unique_together': {('nom', 'categorie')},
            },
        ),
        migrations.CreateModel(
            name='ProfilCandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_entree', models.CharField(blank=True, choices=[('bac', 'Baccalaureat'), ('bac2', 'Bac+2'), ('bac3', 'Bac+3')], max_length=10)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('profil_complete', models.BooleanField(default=False)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_candidat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil candidat',
            },
        ),
        migrations.CreateModel(
            name='ProfilAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_diplome', models.CharField(blank=True, max_length=30)),
                ('specialite', models.CharField(blank=True, max_length=150)),
                ('etablissement', models.CharField(blank=True, max_length=200)),
                ('ville_etablissement', models.CharField(blank=True, max_length=100)),
                ('annee_obtention', models.PositiveIntegerField(blank=True, null=True)),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('moyenne_annee_1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('moyenne_annee_2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('moyenne_annee_3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('modules_principaux', models.TextField(blank=True, help_text='Modules principaux suivis (un par ligne).')),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academique', to='candidats.profilcandidat')),
            ],
            options={
                'verbose_name': 'profil academique',
            },
        ),
        migrations.CreateModel(
            name='NoteAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='candidats.matiere')),
                ('academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='candidats.profilacademique')),
            ],
            options={
                'verbose_name': 'note academique',
                'unique_together': {('academique', 'matiere')},
            },
        ),
        migrations.CreateModel(
            name='InteretCandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to='candidats.centreinteret')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interets', to='candidats.profilcandidat')),
            ],
            options={
                'verbose_name': 'interet du candidat',
                'unique_together': {('profil', 'interet')},
            },
        ),
    ]
