# Generated by Django 5.2.17 on 2026-09-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilcandidat',
            name='objectif',
            field=models.CharField(blank=True, choices=[('universite_publique', 'Poursuivre en universite publique'), ('emploi_public', 'Integrer la fonction publique / un concours'), ('ecole_reconnue', "Integrer une ecole reconnue par l'Etat")], help_text="Universite publique ou emploi public : seules les formations reconnues par l'Etat sont proposees (pas les formations seulement accreditees).", max_length=30, verbose_name='projet'),
        ),
    ]
