# Generated by Django 5.2.17 on 2026-09-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0002_parcours_reconnue_ia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilcandidat',
            name='objectif',
            field=models.CharField(blank=True, choices=[('universite_publique', 'Poursuivre en universite publique'), ('emploi_public', 'Integrer la fonction publique / un concours'), ('ecole_reconnue', "Integrer une ecole reconnue par l'Etat"), ('etudes_privees', 'Etudier dans le secteur prive'), ('emploi_prive', 'Travailler dans le secteur prive')], help_text="Universite publique, fonction publique et ecole reconnue : uniquement des formations reconnues par l'Etat. Secteur prive (etudes ou emploi) : les formations accreditees sont aussi proposees.", max_length=30, verbose_name='projet'),
        ),
    ]
