# Generated by Django 5.2.17 on 2026-09-13 10:46

from django.db import migrations, models


def regrouper_objectifs(apps, schema_editor):
    Profil = apps.get_model('candidats', 'ProfilCandidat')
    publics = ('universite_publique', 'emploi_public', 'ecole_reconnue')
    prives = ('etudes_privees', 'emploi_prive')
    Profil.objects.filter(objectif__in=publics).update(objectif='public')
    Profil.objects.filter(objectif__in=prives).update(objectif='prive')


class Migration(migrations.Migration):

    dependencies = [
        ('candidats', '0003_objectifs_prive_reconnue'),
    ]

    operations = [
        migrations.RunPython(regrouper_objectifs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profilcandidat',
            name='objectif',
            field=models.CharField(blank=True, choices=[('public', "Secteur public / ecole reconnue par l'Etat"), ('prive', 'Secteur prive (etudes ou emploi)')], help_text="Public / ecole reconnue : formations reconnues par l'Etat. Prive : les formations accreditees sont aussi proposees.", max_length=30, verbose_name='projet'),
        ),
    ]
