# Generated by Django 5.2.17 on 2026-09-11 19:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidats', '0001_initial'),
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('type_question', models.CharField(choices=[('choix_unique', 'Choix unique'), ('choix_multiple', 'Choix multiple')], default='choix_unique', max_length=20)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('version', models.PositiveIntegerField(default=1)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "questionnaire d'orientation",
            },
        ),
        migrations.CreateModel(
            name='OptionReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=300)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='orientation.question')),
            ],
            options={
                'verbose_name': 'option de reponse',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='orientation.questionnaire'),
        ),
        migrations.CreateModel(
            name='TentativeQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Termine')], default='en_cours', max_length=20)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to='candidats.profilcandidat')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to='orientation.questionnaire')),
            ],
            options={
                'verbose_name': 'tentative de questionnaire',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='candidats.profilcandidat')),
                ('tentative', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommandation', to='orientation.tentativequestionnaire')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PonderationOptionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.PositiveIntegerField(default=1)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponderations_options', to='formations.formation')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponderations', to='orientation.optionreponse')),
            ],
            options={
                'verbose_name': 'ponderation option / formation',
                'unique_together': {('option', 'formation')},
            },
        ),
        migrations.CreateModel(
            name='RecommandationFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_academique', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_interets', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_questionnaire', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_final', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('explication', models.JSONField(blank=True, default=dict, help_text='Facteurs ayant contribue au score (pour la transparence).')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='formations.formation')),
                ('recommandation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='orientation.recommandation')),
            ],
            options={
                'verbose_name': 'formation recommandee',
                'ordering': ['-score_final'],
                'unique_together': {('recommandation', 'formation')},
            },
        ),
        migrations.CreateModel(
            name='ReponseCandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientation.optionreponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientation.question')),
                ('tentative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='orientation.tentativequestionnaire')),
            ],
            options={
                'verbose_name': 'reponse du candidat',
                'unique_together': {('tentative', 'question', 'option')},
            },
        ),
    ]
