# Generated by Django 5.2.17 on 2026-09-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommandation',
            name='avis_ia',
            field=models.TextField(blank=True, help_text='Commentaire personnalise genere par le conseiller IA (Groq).'),
        ),
    ]
