# Generated by Django 5.2.17 on 2026-09-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientation', '0002_parcours_reconnue_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativequestionnaire',
            name='personnalisation',
            field=models.JSONField(blank=True, default=dict, help_text="Questions/options reformulees par l'IA selon le profil."),
        ),
    ]
